### ISSUE TITLE
"For developers" section in README.md is bad

### ISSUE THREAD

**Issue by mdtrooper** [MaxBittker/sandspiel-studio#146]
I am trying to run sandspiel-studio locally, but I can not.

```shell
panacea@portatil:/tmp/sandspiel-studio$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @blockly/plugin-cross-tab-copy-paste@1.0.5" has incorrect peer dependency "blockly@^7 - 8".
warning "next-query-params > use-query-params@1.2.3" has unmet peer dependency "query-string@>=5.1.1".
warning "next-query-params > use-query-params > serialize-query-params@1.3.6" has unmet peer dependency "query-string@>=5.1.1".
warning " > raw-loader@4.0.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "@typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
$ cp -r node_modules/blockly/media public/media
Done in 7.74s.
panacea@portatil:/tmp/sandspiel-studio$ yarn build
yarn run v1.22.19
$ prisma generate
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (3.14.0 | library) to ./node_modules/@prisma/client in 107ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
 ` ``
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
 ` ``
$ next build
info  - Checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

Sentry CLI Plugin: Command failed: /tmp/sandspiel-studio/node_modules/@sentry/cli/sentry-cli releases new Ff5go8bXCGv6b-yiRV546
error: API request failed
  caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.


> Build failed because of webpack errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
panacea@portatil:/tmp/sandspiel-studio$ yarn dev
yarn run v1.22.19
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
wait  - compiling...
warn  - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./src/style/post.css
Warning

(107:3) autoprefixer: start value has mixed support, consider using flex-start instead
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/tmp/sandspiel-studio/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!/tmp/sandspiel-studio/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!/tmp/sandspiel-studio/src/style/post.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 1 items } -> webpack/lib/ModuleWarning -> Warning
warn  - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./src/style/post.css
Warning

(107:3) autoprefixer: start value has mixed support, consider using flex-start instead
wait  - compiling / (client and server)...
wait  - compiling...
warn  - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./src/style/post.css
Warning

(107:3) autoprefixer: start value has mixed support, consider using flex-start instead
Unable to unregister [custom_renderer][renderer] from the registry.
Registering CSS by passing an array of strings was deprecated on September 2021 and will be deleted on September 2022.
Use css.register passing a multiline string instead.
No extension mapping for name "if_mutator" found to unregister
No extension mapping for name "group_mutator" found to unregister
Block definiton "boolean_operation" overwrites previous definition.
No extension mapping for name "operation_mutator" found to unregister
No extension mapping for name "that_mutator" found to unregister
No extension mapping for name "get_r_mutator" found to unregister
No extension mapping for name "set_r_mutator" found to unregister
No extension mapping for name "modify_r_mutator" found to unregister
Error: error: Environment variable not found: PLANETSCALE_PRISMA_DATABASE_URL.
  -->  schema.prisma:8
   | 
 7 |     provider             = "mysql"
 8 |     url                  = env("PLANETSCALE_PRISMA_DATABASE_URL")
   | 

Validation Error Count: 1
    at Object.loadEngine (/tmp/sandspiel-studio/node_modules/@prisma/client/runtime/index.js:41175:19)
    at async Object.instantiateLibrary (/tmp/sandspiel-studio/node_modules/@prisma/client/runtime/index.js:41104:5)
error - uncaughtException: Error: error: Environment variable not found: PLANETSCALE_PRISMA_DATABASE_URL.
  -->  schema.prisma:8
   | 
 7 |     provider             = "mysql"
 8 |     url                  = env("PLANETSCALE_PRISMA_DATABASE_URL")
   | 

Validation Error Count: 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Mecanix-Creations** [comment]
same here, plz fix I wanna use it locally, mine looks like this V V
`ready - started server on 0.0.0.0:3000, url: http://localhost:3000
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: error: Environment variable not found: PLANETSCALE_PRISMA_DATABASE_URL.
  -->  schema.prisma:8
   |
 7 |     provider             = "mysql"
 8 |     url                  = env("PLANETSCALE_PRISMA_DATABASE_URL")
   |

Validation Error Count: 1
    at Object.loadEngine (C:\Users\neall\sandspiel-studio\node_modules\@prisma\client\runtime\index.js:41175:19)
    at async Object.instantiateLibrary (C:\Users\neall\sandspiel-studio\node_modules\@prisma\client\runtime\index.js:41104:5)
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
wait  - compiling...
warn  - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./src/style/post.css
Warning

(107:3) autoprefixer: start value has mixed support, consider using flex-start instead
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|C:\Users\neall\sandspiel-studio\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[3].oneOf[8].use[1]!C:\Users\neall\sandspiel-studio\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[3].oneOf[8].use[2]!C:\Users\neall\sandspiel-studio\src\style\post.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 1 items } -> webpack/lib/ModuleWarning -> Warning`
